version: 2

sphinx:
  builder: html
  configuration: conf.py
  fail_on_warning: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

formats:
  - pdf
  - epub

python:
  install:
  - requirements: docs/requirements.txt
